### ISSUE TITLE
[Feature] Implement HTTPS LoadBalancing 

### ISSUE THREAD

**Issue by scott45** [andela/vof-deployment-scripts#13]
What is the issue?
Redirect all HTTP traffic to HTTPS when using the HTTP(S) Load Balancer on Google Compute Engine.

HTTP/HTTPS Load Balancing set up on Google Compute Engine with 2 Global Forwarding Rules (HTTP and HTTPS). Each rule points to a back-end service with a protocol of HTTP. 

Workaround
HTTP to HTTPS redirection (using SSL) is currently not supported through HTTP/HTTPS load balancer. The redirection needs to be configured on your web server (apache, nginx etc).

Debug log output
N/A.

Expected Behavior
All requests to http://* should go to https://*. 

Steps to reproduce
N/A.

**Comment by Lemmah** [comment]
Due to the fact that GCP has not implemented http to https redirect on their load balancer, this was handled at the backends level with each instance forcing https redirect. It has been made possible with the rails `config.force_ssl` configuration.

**Comment by Chidiebube** [comment]
@Lemmah can you make reference to the github pr that handled this ?
