### ISSUE TITLE
[Feature] Slack alert when testing job complete

### ISSUE THREAD

**Issue by SProjects** [andela/vof-deployment-scripts#9]
**What is the issue?**
The VOF developers would like to receive a Slack alert/message when ever CircleCI completes the test job. Currently this does not happen. 

**Workaround**
N/A

**Debug log output**
N/A

**Expected Behavior**
A Slack alert/message is sent to the `vof-tracker-deploy` slack channel whenever the test job on CircleCi completes successfully or fails.

**Steps to reproduce**
N/A

**Comment by Lemmah** [comment]
This has been implemented on the .circleci configuration files on the tracker repository itself. Working as expected now.
